# Generated by Django 4.2.28 on 2026-03-10 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0002_videogeneration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('preview_image', models.ImageField(help_text='Thumbnail shown in the avatar selection grid.', upload_to='avatars/previews/')),
                ('source_video', models.FileField(help_text='Source video used by the Wav2Lip pipeline.', upload_to='avatars/source/')),
                ('description', models.TextField(blank=True, default='', help_text='Short description shown below the avatar card.')),
                ('category', models.CharField(choices=[('presenter', 'Presenter'), ('teacher', 'Teacher'), ('business', 'Business'), ('narrator', 'Narrator'), ('influencer', 'Influencer'), ('custom', 'Custom')], default='presenter', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive avatars are hidden from the selection UI.')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first in the grid.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Avatar',
                'verbose_name_plural': 'Avatars',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='videogeneration',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_videos', to='video_app.avatar'),
        ),
    ]
