# Generated by Django 4.2.28 on 2026-03-10 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video_app', '0003_avatar_videogeneration_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('presenter', 'Presenter'), ('teacher', 'Teacher'), ('business', 'Business'), ('narrator', 'Narrator'), ('influencer', 'Influencer'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('preview_image', models.ImageField(blank=True, help_text='Thumbnail shown in the avatar grid.', null=True, upload_to='user_avatars/previews/')),
                ('source_video', models.FileField(help_text='Source video used by the Wav2Lip pipeline.', upload_to='user_avatars/source/')),
                ('is_public', models.BooleanField(default=False, help_text='If True, shared with all users after admin approval.')),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Admin review status. Relevant only for public avatars.', max_length=10)),
                ('review_note', models.TextField(blank=True, default='', help_text='Internal admin note (e.g. rejection reason).')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_avatars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Avatar',
                'verbose_name_plural': 'User Avatars',
                'ordering': ['-created_at'],
            },
        ),
    ]
