# Generated by Django 4.2.28 on 2026-03-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0004_useravatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_cloudinary_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='videogeneration',
            name='audio_file',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='videogeneration',
            name='video_file',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
